apiVersion: apps/v1
kind: Deployment
metadata:
  name: remote-two-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remote-two
  template:
    metadata:
      labels:
        app: remote-two
    spec:
      containers:
        - name: remote-two
          image: cesargdd/kub-remote-two:latest
          ports:
            - containerPort: 3001
          env:
            - name: REMOTE_TWO
              value: "remote-one-service.default"