apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-host-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-host
  template:
    metadata:
      labels:
        app: react-host
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: host-pvc
      containers:
        - name: react-host
          image: cesargdd/kub-react-host:latest
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: data
              mountPath: /usr/share/nginx/html/app/files
        # - name: remote-one
        #   image: cesargdd/kub-remote-one:latest
        #   ports:
        #     - containerPort: 3000
        # - name: remote-two
        #   image: cesargdd/kub-remote-two:latest
        #   ports:
        #     - containerPort: 3001

